### ISSUE TITLE
Network Synchronisation

### ISSUE THREAD

**Issue by AndAntAnd** [ethereumfuture/ethf#2]
For few days wallet can not synchronize with network. v 1.3.3.2 Windows 10 Home 
Pls recommend what shall I do

**Comment by ethereumfuture** [comment]
The chain was broken after very big changes of POW hashrate. In new version 2.0.0.3 chain restored, and it is fully POS now. Synchronisation for new version will be working after most will be upgraded to v2.0.0.3, in nearest days, please upgrade now

**Comment by AndAntAnd** [comment]
That's ok, but where can I get this upgrade? pls provide the link

2018-06-04 15:21 GMT+02:00, ethereumfuture <notifications@github.com>:
> The chain was broken after very big changes of POW hashrate. In new version
> 2.0.0.3 chain restored, and it is fully POS now. Synchronisation for new
> version will be working after most will be upgraded to v2.0.0.3, in nearest
> days, please upgrade now
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/ethereumfuture/ethf/issues/2#issuecomment-394352219


-- 
Best regards,

A. Andreev
